name: Windows

on: 
  push:

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: set env vars
      run: |
        if [ ${{github.ref_name}} == 'juce8' ]; then
          echo "GUI_BRANCH=development-juce8" >> "$GITHUB_ENV"
          echo "GUI_LIB_VERSION=v1.0.0-dev" >> "$GITHUB_ENV"
        elif [ ${{github.ref_name}} == 'testing-juce8' ]; then
          echo "GUI_BRANCH=testing-juce8" >> "$GITHUB_ENV"
          echo "GUI_LIB_VERSION=v1.0.0-alpha" >> "$GITHUB_ENV"
        else
          echo "Invalid branch : ${{github.ref_name}}"
          exit 1
        fi
      shell: bash
    - name: setup
      run: |
        cd ../..
        git clone https://github.com/open-ephys/plugin-GUI.git --branch $GUI_BRANCH
        cd plugin-GUI/Build
        cmake -G "Visual Studio 17 2022" -A x64 .. 
        mkdir Release && cd Release
        curl -L https://openephysgui.jfrog.io/artifactory/Libraries/open-ephys-lib-$GUI_LIB_VERSION.zip --output open-ephys-lib.zip 
        unzip open-ephys-lib.zip
      shell: bash
    - name: configure
      run: |
        cd Build
        cmake -G "Visual Studio 17 2022" -A x64 .. 
      shell: bash
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: build
      run: |
        msbuild Build/INSTALL.vcxproj -p:Configuration=Release -p:Platform=x64
      shell: cmd
# TODO: Perform some basic testing before publishing...
#    - name: test
#      run: cd build && ctest
    - name: deploy
      if: github.ref == 'refs/heads/testing-juce8'
      env:
        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
        build_dir: "Build/Release"
        package: ZMQInterface-windows
      run: |
        plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]*" | tail -1)
        tag=$(grep -w Source/OpenEphysLib.cpp -e 'info->libVersion' | grep -Eo "[0-9]+.[0-9]+.[0-9]+")
        new_plugin_ver=$tag-API$plugin_api
        mkdir plugins
        cp $build_dir/*.dll plugins
        mkdir shared
        cp -r libs/windows/bin/x64/* shared
        zipfile=${package}_${new_plugin_ver}.zip
        powershell Compress-Archive -Path "plugins" -DestinationPath ${zipfile}
        powershell Compress-Archive -U -Path "shared" -DestinationPath ${zipfile}
        curl -H "X-JFrog-Art-Api:$artifactoryApiKey" -T $zipfile "https://openephys.jfrog.io/artifactory/ZMQInterface-plugin/windows/$zipfile"
      shell: bash